version: 2
jobs:
  build:
    working_directory: ~/django-page-components
    docker:
      - image: ubuntu:16.04
    steps:
      - run: apt-get update && apt-get install -y git python2.7-dev python3.5-dev python-pip
      - run: pip install flake8 tox codecov
      - checkout
      - run: pip install -e .
      - run: flake8 ./src
      - run: rm -f coverage.xml
      - run: tox
      - run: codecov
